version: '3.8'

services:
  web:
    build: .
    ports:
      - "${APP_PORT:-5000}:${APP_PORT:-5000}"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-hospital_db}
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_PORT=${DB_PORT:-5432}
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-False}
      - APP_HOST=${APP_HOST:-0.0.0.0}
      - APP_PORT=${APP_PORT:-5000}
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME:-hospital_db}
      - POSTGRES_USER=${DB_USER:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data: